/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/publish`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/skeleton/styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/skeleton/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/skeleton/index.web`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-trips` | `/my-trips`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/publish-placeholder` | `/publish-placeholder`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/detail/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/publish`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/skeleton/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/skeleton/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/skeleton/index.web`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/my-trips` | `/my-trips`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/publish-placeholder` | `/publish-placeholder`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/detail/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/publish${`?${string}` | `#${string}` | ''}` | `/../components/ui/skeleton/styles${`?${string}` | `#${string}` | ''}` | `/../components/ui/skeleton/index${`?${string}` | `#${string}` | ''}` | `/../components/ui/skeleton/index.web${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/my-trips${`?${string}` | `#${string}` | ''}` | `/my-trips${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/publish-placeholder${`?${string}` | `#${string}` | ''}` | `/publish-placeholder${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/publish`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/skeleton/styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/skeleton/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/skeleton/index.web`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-trips` | `/my-trips`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/publish-placeholder` | `/publish-placeholder`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | `/+not-found` | `/detail/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/detail/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
